title: Bhargav Madishetti
logo: https://th.bing.com/th/id/OIP.F_oSOvBmwwO0XXx5r9-Z4AHaEo?w=265&h=180&c=7&r=0&o=5&dpr=1.5&pid=1.7
description: Roadmap to Data Scientist
show_downloads: true
theme: jekyll-theme-minimal
